### ISSUE TITLE
Agregar .gitignore

### ISSUE THREAD

**Issue by tw1ttt3r** [gerhercar21/portfolio#2]
Cuando trabajas proyectos con node, hay que generar un archivo .gitignore el cual nos permite a partir de reglas ignorar archivos o hasta directorios los cuales git no les dara seguimiento, uno de ellos es `node_modules` el cual a traves de comandos de npm o cualquier otro manejador de paquetes se pueden volver a reinstalar, haciendo más ligero tu repo

**Comment by gerhercar21** [comment]
Estimado Pet, olvidé como agregarlo, quedamos que una opción es entrar a https://www.toptal.com/developers/gitignore y poner en el input "Node", darle en "Create" y el código que genere lo agrego al documento que creé previamente llamado .gitignore, pero después, ¿qué sigue?

**Comment by tw1ttt3r** [comment]
Que tal master, le dejo este post donde explica paso a paso la creación del archivo https://www.freecodecamp.org/espanol/news/gitignore-explicado-que-es-y-como-agregar-a-tu-repositorio/

**Comment by gerhercar21** [comment]
Muchas gracias profe! le echo un ojo porque había olvidado cómo hacerlo
