### ISSUE TITLE
Imagenes svg

### ISSUE THREAD

**Issue by tw1ttt3r** [gerhercar21/portfolio#3]
Al revisar el código, encontré que tus imagenes svg les estás colocando los atributos `width` y `height` lo que hace que ese valor este directamente en el elemento, lo que te recomiendo es quitar esos valores y setearlos con css, además tu media query esta colocandoles un porcentaje en relación a ese `width` y `heigth`, así que lo que puedes hacer es, con tus selectores colocales un width y height o en su defecto elimina la media query y solo colocale el porcentaje que debería tener, sin importar la dimensión del dispositivo, siempre se escalará a ese porcentaje

**Comment by gerhercar21** [comment]
NICE !
